import { hash } from "bcryptjs";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
const strongPassword = z.string().min(12, "Use at least 12 characters").max(72).regex(/[A-Z]/, "Include an uppercase letter").regex(/[a-z]/, "Include a lowercase letter").regex(/[0-9]/, "Include a number").regex(/[^A-Za-z0-9]/, "Include a special character");
const schema = z.object({ firstName: z.string().trim().min(2).max(60), lastName: z.string().trim().min(2).max(60), email: z.string().trim().toLowerCase().email(), phone: z.string().trim().max(20).optional(), role: z.enum(["SUPER_ADMIN", "MANAGER", "RECEPTIONIST", "ACCOUNTANT", "HOUSEKEEPER"]), password: strongPassword, confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { message: "Passwords do not match", path: ["confirmPassword"] });
export async function GET() { const user = await getCurrentUser(); if (!user) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); if (!["SUPER_ADMIN", "MANAGER"].includes(user.role)) return NextResponse.json({ message: "Forbidden" }, { status: 403 }); const staff = await prisma.user.findMany({ where: { propertyId: user.propertyId }, select: { id: true, firstName: true, lastName: true, email: true, phone: true, role: true, isActive: true, createdAt: true }, orderBy: { firstName: "asc" } }); return NextResponse.json(staff); }
export async function POST(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); if (!["SUPER_ADMIN", "MANAGER"].includes(user.role)) return NextResponse.json({ message: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ message: parsed.error.issues[0]?.message ?? "Invalid staff details" }, { status: 400 }); if (user.role === "MANAGER" && parsed.data.role === "SUPER_ADMIN") return NextResponse.json({ message: "Managers cannot create Super Administrators" }, { status: 403 }); const exists = await prisma.user.findUnique({ where: { email: parsed.data.email } }); if (exists) return NextResponse.json({ message: "A user with this email already exists" }, { status: 409 }); const passwordHash = await hash(parsed.data.password, 12); const staff = await prisma.$transaction(async (tx) => { const created = await tx.user.create({ data: { firstName: parsed.data.firstName, lastName: parsed.data.lastName, email: parsed.data.email, phone: parsed.data.phone || null, role: parsed.data.role, passwordHash, propertyId: user.propertyId } }); await tx.auditLog.create({ data: { action: "CREATE_STAFF", entity: "User", entityId: created.id, userId: user.id, details: { email: created.email, role: created.role } } }); return created; }); return NextResponse.json({ id: staff.id, firstName: staff.firstName, lastName: staff.lastName, email: staff.email, phone: staff.phone, role: staff.role, isActive: staff.isActive }, { status: 201 }); }
