"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Type={id:string;name:string;capacity:number;basePrice:number}; type Room={id:string;roomNumber:string;floor:string|null;status:string;roomType:Type};
export default function RoomsPage(){
 const [types,setTypes]=useState<Type[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const [a,b]=await Promise.all([fetch("/api/room-types"),fetch("/api/rooms")]);if(a.ok)setTypes(await a.json());if(b.ok)setRooms(await b.json());},[]);useEffect(()=>{load()},[load]);
 async function submit(e:FormEvent<HTMLFormElement>,url:string){e.preventDefault();setMessage("");const form=e.currentTarget;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await r.json();setMessage(data.message??(r.ok?"Saved successfully":"Unable to save"));if(r.ok){form.reset();load();}}
 async function status(id:string,value:string){await fetch(`/api/rooms/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})});load();}
 const input="w-full rounded-xl border border-slate-300 px-3 py-2.5";
 return <main className="p-5 md:p-8"><h1 className="text-3xl font-black">Rooms</h1><p className="text-slate-500">Configure room categories, rates and live availability.</p>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}<div className="mt-7 grid gap-6 xl:grid-cols-2"><form onSubmit={e=>submit(e,"/api/room-types")} className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="font-bold">Add room type</h2><input className={input} name="name" required placeholder="Deluxe Double"/><textarea className={input} name="description" placeholder="Description"/><div className="grid grid-cols-2 gap-3"><input className={input} name="capacity" type="number" min="1" required placeholder="Capacity"/><input className={input} name="basePrice" type="number" min="1" step="0.01" required placeholder="Rate in ZMW"/></div><button className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Save room type</button></form><form onSubmit={e=>submit(e,"/api/rooms")} className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="font-bold">Add room</h2><div className="grid grid-cols-2 gap-3"><input className={input} name="roomNumber" required placeholder="Room number"/><input className={input} name="floor" placeholder="Floor"/></div><select className={input} name="roomTypeId" required><option value="">Select room type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name} â€” K {t.basePrice}</option>)}</select><button className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">Add room</button></form></div><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rooms.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><p className="text-2xl font-black">Room {r.roomNumber}</p><p className="text-sm text-slate-500">{r.roomType.name} Â· K {r.roomType.basePrice}</p></div><span className="text-xs text-slate-500">{r.floor||"â€”"}</span></div><select value={r.status} onChange={e=>status(r.id,e.target.value)} className="mt-5 w-full rounded-xl border px-3 py-2"><option>AVAILABLE</option><option>OCCUPIED</option><option>RESERVED</option><option>CLEANING</option><option>MAINTENANCE</option><option>OUT_OF_SERVICE</option></select></article>)}</section>{rooms.length===0&&<div className="mt-7 rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No rooms added yet.</div>}</main>;
}
