"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Expense = { id: string; category: string; description: string; amount: number; expenseDate: string };
export default function ExpensesPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/expenses"); if (response.ok) setExpenses(await response.json()); }, []);
  useEffect(() => { load(); }, [load]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const response = await fetch("/api/expenses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const result = await response.json(); setMessage(response.ok ? "Expense recorded successfully" : result.message); if (response.ok) { form.reset(); load(); } }
  const total = expenses.reduce((sum, expense) => sum + expense.amount, 0); const input = "w-full rounded-xl border border-slate-300 px-3 py-2.5";
  return <main className="p-5 md:p-8"><h1 className="text-3xl font-black">Expenses</h1><p className="text-slate-500">Record and monitor property operating costs.</p><form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2 xl:grid-cols-4"><select name="category" className={input}><option>UTILITIES</option><option>SUPPLIES</option><option>MAINTENANCE</option><option>SALARIES</option><option>TRANSPORT</option><option>MARKETING</option><option>TAXES</option><option>OTHER</option></select><input name="description" required placeholder="Description" className={input}/><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount in ZMW" className={input}/><input name="expenseDate" type="date" required className={input}/><button className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white md:col-span-2 xl:col-span-4">Record expense</button></form>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}<div className="mt-6 rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Total recorded expenses</p><p className="text-3xl font-black">K {total.toLocaleString()}</p></div><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Date</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody>{expenses.map((expense)=><tr key={expense.id} className="border-t"><td className="p-4">{new Date(expense.expenseDate).toLocaleDateString()}</td><td>{expense.category.replaceAll("_"," ")}</td><td>{expense.description}</td><td className="font-bold">K {expense.amount.toLocaleString()}</td></tr>)}</tbody></table></div></main>;
}
